export const DEAL_FIELDS_MAP = () => [
  { name: 'First Name', value: 'firstName' },
  { name: 'Last Name', value: 'lastName' },
  { name: 'Phone', value: 'phone'},
  { name: 'Email', value: 'email' },
  { name: 'Job type', value: 'jobType' },
  { name: 'Job source', value: 'jobSource' },
  { name: 'Job comment', value: 'jobComment'},
  { name: 'Address', value: 'address' },
  { name: 'City', value: 'city' },
  { name: 'State', value: 'state' },
  { name: 'Zip code', value: 'zipCode' },
  { name: 'Area', value: 'area' },
  { name: 'Job date', value: 'jobDate' },
  { name: 'Job start time', value: 'jobStartTime' },
  { name: 'Job end time', value: 'jobEndTime' },
  { name: 'Job number', value: 'jobNumber' },
  { name: 'Job ID', value: 'jobId' },
  { name: `Tampa Technician`, value: 'technician' },
  { name: `Miami Technician`, value: 'technician' },
  { name: `Arizona Technician`, value: 'technician' },
  { name: `Florida Technician`, value: 'technician' },
]